spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: wattagatta
  rabbitmq:
    port: 5672
    username: guest
    password: guest
    host: localhost

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  jwt:
    secret: ${JWT_SECRET_KEY}
      #    access-token-validity: 360000000 # 100시간
      #    refresh-token-validity: 604800000 # 7일
      